# Generated by Django 5.0.3 on 2024-05-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shedule',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='shedule',
            new_name='schedule',
        ),
    ]
