# Generated by Django 5.0.3 on 2024-05-20 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='friday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first', models.TextField(max_length=255, verbose_name='первая пара')),
                ('second', models.TextField(max_length=255, verbose_name='вторая пара')),
                ('third', models.TextField(max_length=255, verbose_name='третья пара')),
                ('forth', models.TextField(max_length=255, verbose_name='четвертая пара')),
                ('fifth', models.TextField(max_length=255, verbose_name='пятая пара')),
                ('sixth', models.TextField(max_length=255, verbose_name='шестая пара')),
                ('seventh', models.TextField(max_length=255, verbose_name='седьмая пара')),
                ('eighth', models.TextField(max_length=255, verbose_name='восьмая пара')),
            ],
        ),
        migrations.CreateModel(
            name='monday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first', models.TextField(max_length=255, verbose_name='первая пара')),
                ('second', models.TextField(max_length=255, verbose_name='вторая пара')),
                ('third', models.TextField(max_length=255, verbose_name='третья пара')),
                ('forth', models.TextField(max_length=255, verbose_name='четвертая пара')),
                ('fifth', models.TextField(max_length=255, verbose_name='пятая пара')),
                ('sixth', models.TextField(max_length=255, verbose_name='шестая пара')),
                ('seventh', models.TextField(max_length=255, verbose_name='седьмая пара')),
                ('eighth', models.TextField(max_length=255, verbose_name='восьмая пара')),
            ],
        ),
        migrations.CreateModel(
            name='saturday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first', models.TextField(max_length=255, verbose_name='первая пара')),
                ('second', models.TextField(max_length=255, verbose_name='вторая пара')),
                ('third', models.TextField(max_length=255, verbose_name='третья пара')),
                ('forth', models.TextField(max_length=255, verbose_name='четвертая пара')),
                ('fifth', models.TextField(max_length=255, verbose_name='пятая пара')),
                ('sixth', models.TextField(max_length=255, verbose_name='шестая пара')),
                ('seventh', models.TextField(max_length=255, verbose_name='седьмая пара')),
                ('eighth', models.TextField(max_length=255, verbose_name='восьмая пара')),
            ],
        ),
        migrations.CreateModel(
            name='thursday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first', models.TextField(max_length=255, verbose_name='первая пара')),
                ('second', models.TextField(max_length=255, verbose_name='вторая пара')),
                ('third', models.TextField(max_length=255, verbose_name='третья пара')),
                ('forth', models.TextField(max_length=255, verbose_name='четвертая пара')),
                ('fifth', models.TextField(max_length=255, verbose_name='пятая пара')),
                ('sixth', models.TextField(max_length=255, verbose_name='шестая пара')),
                ('seventh', models.TextField(max_length=255, verbose_name='седьмая пара')),
                ('eighth', models.TextField(max_length=255, verbose_name='восьмая пара')),
            ],
        ),
        migrations.CreateModel(
            name='tuesday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first', models.TextField(max_length=255, verbose_name='первая пара')),
                ('second', models.TextField(max_length=255, verbose_name='вторая пара')),
                ('third', models.TextField(max_length=255, verbose_name='третья пара')),
                ('forth', models.TextField(max_length=255, verbose_name='четвертая пара')),
                ('fifth', models.TextField(max_length=255, verbose_name='пятая пара')),
                ('sixth', models.TextField(max_length=255, verbose_name='шестая пара')),
                ('seventh', models.TextField(max_length=255, verbose_name='седьмая пара')),
                ('eighth', models.TextField(max_length=255, verbose_name='восьмая пара')),
            ],
        ),
        migrations.CreateModel(
            name='wednesday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first', models.TextField(max_length=255, verbose_name='первая пара')),
                ('second', models.TextField(max_length=255, verbose_name='вторая пара')),
                ('third', models.TextField(max_length=255, verbose_name='третья пара')),
                ('forth', models.TextField(max_length=255, verbose_name='четвертая пара')),
                ('fifth', models.TextField(max_length=255, verbose_name='пятая пара')),
                ('sixth', models.TextField(max_length=255, verbose_name='шестая пара')),
                ('seventh', models.TextField(max_length=255, verbose_name='седьмая пара')),
                ('eighth', models.TextField(max_length=255, verbose_name='восьмая пара')),
            ],
        ),
        migrations.CreateModel(
            name='shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_friday', to='main.friday')),
                ('monday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_monday', to='main.monday')),
                ('saturday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_saturday', to='main.saturday')),
                ('thursday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_thursday', to='main.thursday')),
                ('tuesday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_tuesday', to='main.tuesday')),
                ('wednesday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_wednesday', to='main.wednesday')),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.TextField(blank=True, max_length=20, unique=True, verbose_name='название группы')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='слаг группы')),
                ('dep_number', models.TextField(blank=True, max_length=255, verbose_name='номер факультета')),
                ('faculty', models.TextField(blank=True, max_length=255, verbose_name='название факультета')),
                ('shedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_shedule', to='main.shedule')),
            ],
        ),
    ]
