# Generated by Django 5.0.3 on 2024-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_groups_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='cтатус'),
        ),
    ]
