# Generated by Django 5.0.3 on 2024-07-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedulechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbrequest', models.TextField(max_length=255, verbose_name='запрос')),
                ('execution', models.TextField(max_length=255, verbose_name='изменение')),
            ],
        ),
    ]
