# Generated by Django 5.0.3 on 2024-07-06 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_schedulechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, verbose_name='категория')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='hashtags',
            field=models.TextField(blank=True, max_length=255, verbose_name='хештеги'),
        ),
        migrations.AddField(
            model_name='news',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categories'),
        ),
        migrations.CreateModel(
            name='GroupsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.TextField(blank=True, max_length=255, verbose_name='хештеги')),
                ('body', models.TextField(verbose_name='содержание')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categories')),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.groups')),
            ],
        ),
    ]
