# Generated by Django 5.0.3 on 2024-07-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/main/images/news/')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.news')),
            ],
        ),
    ]
